name: Deploy Vue to GitHub Pages

on:
  push:
    branches:
      - master  # 在推送到 master 分支时触发

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # - name: Switch to vue directory
      #   working-directory: ./REA/vue_rea  # 指定 Vue 项目所在的子文件夹

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install
        working-directory: vue_rea\  # 指定 Vue 项目所在的子文件夹

      - name: Build project
        run: npm run build  # 生成 Vue 静态文件
        working-directory: vue_rea\  # 指定 Vue 项目所在的子文件夹

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_CUSTOM_TOKEN }}
          publish_dir: vue_rea\dist\  # Vue 项目的静态文件目录
